# Generated by Django 5.1.7 on 2025-04-18 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0002_customuser_bio_customuser_email_notifications'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='bio',
        ),
    ]
