# Generated by Django 5.1.7 on 2025-04-18 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0004_alter_customuser_user_bio_userprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
