# Generated by Django 5.1.7 on 2025-04-20 06:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0007_customuser_nickname'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(blank=True, max_length=500, null=True)),
                ('block_type', models.CharField(choices=[('harassment', 'Harassment'), ('spam', 'Spam'), ('inappropriate', 'Inappropriate Content'), ('other', 'Other')], default='other', max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('expired', 'Expired'), ('appealed', 'Appealed')], default='active', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('unblocked_at', models.DateTimeField(blank=True, null=True)),
                ('block_duration', models.DurationField(blank=True, help_text='Duration of the block, null means indefinite', null=True)),
                ('report_count', models.PositiveIntegerField(default=0)),
                ('is_permanent', models.BooleanField(default=False)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('blocked_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocked_by_users', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocked_users', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'status'], name='Accounts_bl_user_id_067813_idx'), models.Index(fields=['blocked_user', 'status'], name='Accounts_bl_blocked_5d885b_idx'), models.Index(fields=['block_type', 'status'], name='Accounts_bl_block_t_bda723_idx')],
                'unique_together': {('user', 'blocked_user')},
            },
        ),
    ]
