# Generated by Django 5.1.7 on 2025-04-11 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NetSpace', '0002_userposts_postshare_postcomment_userstory_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userposts',
            name='post_image',
            field=models.ImageField(blank=True, null=True, upload_to='posts'),
        ),
    ]
