# Generated by Django 5.1.7 on 2025-04-11 13:10

import NetSpace.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NetSpace', '0003_alter_userposts_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userposts',
            name='post_image',
            field=models.ImageField(blank=True, null=True, upload_to=NetSpace.models.post_image_path),
        ),
    ]
