# Generated by Django 5.1.7 on 2025-04-18 18:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NetSpace', '0005_videocall_voicecall'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Rooms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_name', models.CharField(max_length=100)),
                ('room_description', models.TextField()),
                ('room_image', models.ImageField(blank=True, null=True, upload_to='room_images')),
                ('room_type', models.CharField(choices=[('public', 'Public'), ('private', 'Private')], max_length=50)),
                ('room_category', models.CharField(choices=[('gaming', 'Gaming'), ('education', 'Education'), ('music', 'Music'), ('general', 'General'), ('technology', 'Technology'), ('sports', 'Sports')], default='general', max_length=50)),
                ('room_status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('closed', 'Closed')], default='active', max_length=20)),
                ('participant_count', models.PositiveIntegerField(default=0)),
                ('max_participants', models.PositiveIntegerField(default=100)),
                ('is_featured', models.BooleanField(default=False)),
                ('password', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Room',
                'verbose_name_plural': 'Rooms',
                'ordering': ['-created_at'],
            },
        ),
    ]
