# Generated by Django 5.1.7 on 2025-04-18 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NetSpace', '0006_rooms'),
    ]

    operations = [
        migrations.AddField(
            model_name='rooms',
            name='room_code',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='rooms',
            name='room_id',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True),
        ),
    ]
