# Generated by Django 5.1.7 on 2025-04-20 20:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NetSpace', '0010_alter_notification_notification_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='related_post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='NetSpace.userposts'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('follow', 'Follow'), ('follow_request', 'Follow Request'), ('follow_accept', 'Follow Request Accepted'), ('follow_back', 'Follow Back'), ('follow_request_rejected', 'Follow Request Rejected'), ('new_follower', 'New Follower'), ('unfollow', 'Unfollowed'), ('new_post', 'New Post'), ('post_like', 'Post Like'), ('post_comment', 'Post Comment'), ('post_share', 'Post Share'), ('post_repost', 'Post Repost'), ('live_stream', 'Live Stream Started')], max_length=50),
        ),
    ]
