# Generated by Django 5.1.7 on 2025-04-20 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NetSpace', '0011_notification_related_post_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='comment_content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
